### ISSUE TITLE
Scaffolding page - dead links

### ISSUE THREAD

**Issue by eyalroz** [cleidigh/ThunderStorm#2]
The bottom links on the "scaffolding" page of this repo:

https://github.com/cleidigh/ThunderStorm/blob/master/examples/scaffolds/README.md

are dead...

**Comment by ernierasta** [comment]
@cleidigh can You provide those examples again? They would be very useful, especially now, when we are hunting for every example how to write MailExtension extensions ... Thank You!

**Comment by cleidigh** [comment]
@eyalroz 
@ernierasta 
My apologies for these "unfinished items"  since I started this repository have gotten overwhelmed with the other areas.  I am hoping to get back to it in parallel with doing the conversion exercise.
@ernierasta - a group of extension developers is going to go through the conversion exercise once we pick a representative extension to convert.  If you would like to participate in any way including just being a "observer" that's fine. just let me know .
Christopher

**Comment by ernierasta** [comment]
@cleidigh  no need to apology, we are all doing this in our free time. Thank You for invitation, but I am not right person for this. I am big fan of TB, but not using it. In past I made very primitive plugin for TB and I will need to create one in the future, so that's why I am interested in "how-tos". My knowledge about TB extensions is basically non-existant. ;-)

And to be honest, I am little scare about turning off support for legacy plugins. While it had to be done I am afraid there is not enough examples, how-to's, tutorials for devs like me, which are not interested in becoming TB guru, but want by able quickstart quickly. If I google: "thunderbird create addon" first link:

https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Thunderbird_extensions/Building_a_Thunderbird_extension

And there is not link to actual API description, nor tutorial. They exist and I found them, but it not so easy. 

I may complain in wrong place ... so sorry about it.

**Comment by cleidigh** [comment]
@ernierasta 
I think you will benefit from our exercise even if you do not participate.  Part of the effort is to consolidate and improve the documentation.  Your comments above are absolutely correct in something that were trying to work on.

I am still hoping to improve this repository when I have more time.

**Comment by ernierasta** [comment]
Thanx for info, will check it out for sure!

**Comment by jobisoft** [comment]
Dead links have been removed.
